# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "printf 'VITE_API_URL=%s\\n' \"$VITE_API_URL\" > .env.production",
  "npm run build"
]

[start]
cmd = "npm run start"

[variables]
NODE_VERSION = "20"