import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("/chat", "routes/chat.tsx"),
  route("/login", "routes/login.tsx"),
  route("/verify", "routes/verify.tsx"),
  route("/forgot-password", "routes/forgot-password.tsx"),
  route("/reset-password", "routes/reset-password.tsx"),
  route("/admin/users", "routes/admin/users.tsx"),
  route("/categorias", "routes/categorias.tsx"),
  route("/cuentas", "routes/cuentas.tsx"),
  route("/presupuestos", "routes/presupuestos.tsx"),
  route("/transacciones", "routes/transacciones.tsx"),
  route("/deseos", "routes/deseos.tsx"),
  route("/metricas", "routes/metricas.tsx"),
  route("/analisis", "routes/analisis.tsx"),
  route("/simulador", "routes/simulador.tsx"),
  route("/deudas", "routes/deudas.tsx"),
  route("/fijos", "routes/fijos.tsx"),
  route("/dolar", "routes/dolar.tsx"),
  route("/documentos", "routes/documentos.tsx"),
  route("/cuenta", "routes/cuenta.tsx"),
  route("/papelera", "routes/papelera.tsx"),
] satisfies RouteConfig;
